export const LOAD_STATE = 'LOAD_STATE';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const UPDATE_LOADING = 'UPDATE_LOADING';

export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_SOURCE = 'UPDATE_SOURCE';
export const PREV_CANDIDATE = 'PREV_CANDIDATE';
export const NEXT_CANDIDATE = 'NEXT_CANDIDATE';

export const UPDATE_MODE = 'UPDATE_MODE';
export const TOGGLE_ACTION_SELECTION = 'TOGGLE_ACTION_SELECTION';

export const UPDATE_ACTION_QUERY = 'UPDATE_ACTION_QUERY';
export const UPDATE_ACTIONS = 'UPDATE_ACTIONS';
export const PREV_ACTION = 'PREV_ACTION';
export const NEXT_ACTION = 'NEXT_ACTION';
