export const LOAD_STATE = 'LOAD_STATE';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_SOURCE = 'UPDATE_SOURCE';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const PREV_CANDIDATE = 'PREV_CANDIDATE';
export const NEXT_CANDIDATE = 'NEXT_CANDIDATE';
